name: AsriaCombat
author: NCH
version: 1.0
main: me.nch.asriacombat.AsriaCombat
load: POSTWORLD

commands:
    listmodules:
        description: List the modules and their health effects.
    listplayers:
        description: List the players that are stored in the server's memory.